version: '3.8'
services:
  spark:
    image: bitnami/spark:latest
    volumes:
      - ./src:/app
      - ./data:/data
      - ./requirements.txt:/app/requirements.txt
    environment:
      - SPARK_MASTER_HOST=localhost  
      - SPARK_MASTER_PORT=7077
    command: bash -c "pip install -r /app/requirements.txt && spark-submit --master 'local[*]' /app/elasticsearch_ingest.py"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - movie_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - movie_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - movie_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge